import os
import subprocess
from glob import glob

def generate_graph():
    print("--- Al-Mizan ETL Pipeline ---")
    
    # 1. Ensure output directory
    os.makedirs("output", exist_ok=True)
    
    # 2. Run Extractors
    print("[1/3] Running Quran Extractor...")
    subprocess.run(["python3", "extract_quran.py"], check=True)
    
    print("[2/3] Running Hadith Extractor...")
    subprocess.run(["python3", "extract_hadith.py"], check=True)

    print("[2.5/3] Running Morphology Extractor...")
    subprocess.run(["python3", "extract_morphology.py"], check=True)
    
    # 3. Combine Outputs
    print("[3/3] Combining into Master Ingest Script...")
    filenames = ["output/quran_nodes.surql", "output/hadith_nodes.surql", "output/morphology.surql"]
    
    with open("output/ingest.surql", "w") as outfile:
        outfile.write("-- AL-MIZAN MASTER INGEST SCRIPT\n")
        outfile.write("-- Generated by almizan-etl pipeline\n\n")
        
        for fname in filenames:
            with open(fname) as infile:
                outfile.write(f"\n-- SOURCE: {fname}\n")
                outfile.write(infile.read())
                outfile.write("\n")
                
    print(f"SUCCESS: Pipeline Complete. Master script at 'output/ingest.surql'")

if __name__ == "__main__":
    generate_graph()
