#!/usr/bin/env python3
"""
transform_tanzil.py

Stage 1 of the Al-Mizan ETL Pipeline.

Responsibility:
1. Parse raw Uthmani Quran XML (Tanzil.net standard).
2. Calculate metadata (Juz numbers, Revelation place).
3. Transform Hadith (Nawawi 40) JSON.
4. Generate 'ingest.surql' for bulk database loading.

Inputs:
- data/quran-uthmani.xml
- data/quran-data.xml
- data/hadith40.json

Outputs:
- output/quran_full.surql
- output/hadith_nawawi.surql
- output/ingest.surql (Combined master script)
"""
import xml.etree.ElementTree as ET
import json
import os

BASE_DIR = os.path.dirname(__file__)
DATA_DIR = os.path.join(BASE_DIR, "data")
OUTPUT_DIR = os.path.join(BASE_DIR, "output")

def escape_surql(text: str) -> str:
    """Escape single quotes for SurQL strings."""
    if text is None:
        return ""
    return text.replace("\\", "\\\\").replace("'", "\\'")

def parse_tanzil_data():
    """
    Parse Tanzil metadata (XML) and Text file to build structured Quran data.
    """
    xml_path = os.path.join(DATA_DIR, "quran-data.xml")
    text_path = os.path.join(DATA_DIR, "quran-uthmani.xml")
    
    if not os.path.exists(xml_path) or not os.path.exists(text_path):
        print(f"❌ Missing files in {DATA_DIR}")
        return None
        
    print(f"📖 Parsing metadata from {xml_path}...")
    tree = ET.parse(xml_path)
    root = tree.getroot()
    
    suras = []
    for sura in root.findall('.//sura'):
        suras.append({
            'index': int(sura.get('index')),
            'ayas': int(sura.get('ayas')),
            'name': sura.get('name'),
            'type': sura.get('type')  # Meccan/Medinan
        })
        
    print(f"📖 Reading text from {text_path}...")
    with open(text_path, 'r', encoding='utf-8') as f:
        lines = [l.strip() for l in f if l.strip()]
        
    total_verses_meta = sum(s['ayas'] for s in suras)
    total_lines = len(lines)
    
    print(f"   • Metadata expects: {total_verses_meta} verses")
    print(f"   • Text file has:    {total_lines} lines")
    
    if total_lines != total_verses_meta:
        print("⚠️  Mismatch count! Attempting to Align...")
        # Often occurs if Bismillah is not counted or separate lines.
        # But Tanzil standard usually maps 1-to-1.
    
    verses = []
    line_idx = 0
    
    for s in suras:
        sura_num = s['index']
        count = s['ayas']
        place = 'Makkah' if s['type'] == 'Meccan' else 'Madinah'
        
        for ayah_num in range(1, count + 1):
            if line_idx < total_lines:
                text = lines[line_idx]
                
                # Calculate Juz
                juz = calculate_juz(sura_num, ayah_num)
                
                verses.append({
                    'surah': sura_num,
                    'ayah': ayah_num,
                    'text': text,
                    'juz': juz,
                    'place': place
                })
                line_idx += 1
            else:
                break
                
    return verses

def parse_tanzil_xml():
    # Backwards compatibility wrapper if needed, but we used the new name above
    return parse_tanzil_data()

def calculate_juz(surah: int, ayah: int) -> int:
    """Approximate Juz number based on surah/ayah position."""
    # Juz boundaries (simplified)
    juz_starts = [
        (1, 1), (2, 142), (2, 253), (3, 93), (4, 24),
        (4, 148), (5, 82), (6, 111), (7, 88), (8, 41),
        (9, 93), (11, 6), (12, 53), (14, 1), (15, 1),
        (17, 1), (18, 75), (20, 1), (21, 1), (23, 1),
        (25, 21), (27, 56), (29, 46), (33, 31), (36, 28),
        (39, 32), (41, 47), (46, 1), (51, 31), (78, 1)
    ]
    
    for i, (s, a) in enumerate(reversed(juz_starts)):
        if surah > s or (surah == s and ayah >= a):
            return 30 - i
    return 1

def transform_quran(verses: list):
    """Generate SurQL statements from parsed verses."""
    print("📜 Generating Quran SurQL...")
    
    statements = []
    statements.append("-- QURAN VERSES (Full Corpus)")
    statements.append("-- Source: Tanzil.net Uthmani Script")
    statements.append("-- Generated by transform_tanzil.py")
    statements.append("BEGIN TRANSACTION;")
    statements.append("")
    
    for v in verses:
        text_ar = escape_surql(v['text'])
        verse_id = f"quran_verse:{v['surah']}_{v['ayah']}"
        
        stmt = f"""CREATE {verse_id} SET
    text_uthmani = '{text_ar}',
    surah_number = {v['surah']},
    ayah_number = {v['ayah']},
    juz_number = {v['juz']},
    revelation_place = '{v['place']}',
    mutability = 'CONSTANT';"""
        statements.append(stmt)
        statements.append("")
    
    statements.append("COMMIT TRANSACTION;")
    
    output_path = os.path.join(OUTPUT_DIR, "quran_full.surql")
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(statements))
    
    print(f"   → Generated: {output_path}")
    return len(verses)

def transform_hadith():
    """Transform 40 Nawawi JSON into hadith nodes."""
    print("📜 Generating Hadith SurQL...")
    
    json_path = os.path.join(DATA_DIR, "hadith40.json")
    if not os.path.exists(json_path):
        print(f"   ⚠️ Hadith file not found, skipping.")
        return 0
    
    with open(json_path, 'r', encoding='utf-8') as f:
        hadith_data = json.load(f)
    
    statements = []
    statements.append("-- HADITH (40 Nawawi)")
    statements.append("-- Generated by transform_tanzil.py")
    statements.append("BEGIN TRANSACTION;")
    statements.append("")
    
    for h in hadith_data.get('hadiths', []):
        h_id = h.get('idInBook', h.get('id', 0))
        matn_ar = escape_surql(h.get('arabic', ''))
        
        english_obj = h.get('english', {})
        if isinstance(english_obj, dict):
            narrator = english_obj.get('narrator', '')
            text = english_obj.get('text', '')
            matn_en = escape_surql(f"{narrator} {text}".strip())
        else:
            matn_en = escape_surql(str(english_obj))
        
        hadith_id = f"hadith:nawawi_{h_id}"
        
        stmt = f"""CREATE {hadith_id} SET
    collection = 'Nawawi 40',
    hadith_number = {h_id},
    matn_ar = '{matn_ar}',
    mutability = 'CONSTANT';"""
        statements.append(stmt)
        
        if matn_en:
            trans_id = f"translation:nawawi_{h_id}_en"
            stmt_trans = f"""CREATE {trans_id} SET
    text_en = '{matn_en}',
    translator = 'Various',
    language = 'en';"""
            statements.append(stmt_trans)
            statements.append(f"RELATE {hadith_id} -> translated_as -> {trans_id};")
        
        statements.append("")
    
    statements.append("COMMIT TRANSACTION;")
    
    output_path = os.path.join(OUTPUT_DIR, "hadith_nawawi.surql")
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(statements))
    
    print(f"   → Generated: {output_path}")
    return len(hadith_data.get('hadiths', []))

def generate_master_ingest():
    """Combine all outputs into a single ingest script."""
    print("📜 Generating master ingest script...")
    
    files = ["quran_full.surql", "hadith_nawawi.surql"]
    
    with open(os.path.join(OUTPUT_DIR, "ingest.surql"), 'w', encoding='utf-8') as outfile:
        outfile.write("-- AL-MIZAN MASTER INGEST SCRIPT\n")
        outfile.write("-- Source: Tanzil.net + Nawawi 40\n")
        outfile.write("-- Generated by transform_tanzil.py\n\n")
        
        for fname in files:
            fpath = os.path.join(OUTPUT_DIR, fname)
            if os.path.exists(fpath):
                outfile.write(f"\n-- === {fname} ===\n")
                with open(fpath, 'r', encoding='utf-8') as infile:
                    outfile.write(infile.read())
                outfile.write("\n")
    
    print(f"   → Generated: {os.path.join(OUTPUT_DIR, 'ingest.surql')}")

def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    verses = parse_tanzil_xml()
    if not verses:
        return
    
    verse_count = transform_quran(verses)
    hadith_count = transform_hadith()
    generate_master_ingest()
    
    print(f"\n🎉 DONE!")
    print(f"   • {verse_count} verses")
    print(f"   • {hadith_count} hadiths")
    print(f"\nTo ingest into SurrealDB:")
    print(f"   surreal import --conn http://localhost:8000 -u root -p root --ns idc --db main output/ingest.surql")

if __name__ == "__main__":
    main()
