#!/usr/bin/env python3
"""
transform_to_surql.py
Transforms downloaded JSON into SurQL ingest scripts matching the ontology schema.
"""
import json
import os

BASE_DIR = os.path.dirname(__file__)
DATA_DIR = os.path.join(BASE_DIR, "data")
OUTPUT_DIR = os.path.join(BASE_DIR, "output")

def escape_surql(text: str) -> str:
    """Escape single quotes for SurQL strings."""
    if text is None:
        return ""
    return text.replace("\\", "\\\\").replace("'", "\\'")

def transform_quran():
    """Transform Juz 30 Arabic + English into quran_verse + translation nodes."""
    print("📜 Transforming Quran data...")
    
    # Load Arabic
    with open(os.path.join(DATA_DIR, "juz30_arabic.json"), 'r', encoding='utf-8') as f:
        arabic_data = json.load(f)
    
    # Load English
    with open(os.path.join(DATA_DIR, "juz30_english.json"), 'r', encoding='utf-8') as f:
        english_data = json.load(f)
    
    # Build lookup for English translations
    english_lookup = {}
    for ayah in english_data.get('data', {}).get('ayahs', []):
        key = f"{ayah['surah']['number']}:{ayah['numberInSurah']}"
        english_lookup[key] = ayah['text']
    
    statements = []
    statements.append("-- QURAN VERSES (Juz 30)")
    statements.append("-- Generated by transform_to_surql.py")
    statements.append("BEGIN TRANSACTION;")
    statements.append("")
    
    for ayah in arabic_data.get('data', {}).get('ayahs', []):
        surah = ayah['surah']['number']
        ayah_num = ayah['numberInSurah']
        text_ar = escape_surql(ayah['text'])
        place = ayah['surah'].get('revelationType', 'Meccan')
        place = 'Makkah' if place == 'Meccan' else 'Madinah'
        
        verse_id = f"quran_verse:{surah}_{ayah_num}"
        
        # Create verse node
        stmt = f"""CREATE {verse_id} SET
    text_uthmani = '{text_ar}',
    surah_number = {surah},
    ayah_number = {ayah_num},
    juz_number = 30,
    revelation_place = '{place}',
    mutability = 'CONSTANT';"""
        statements.append(stmt)
        
        # Create translation node + edge
        key = f"{surah}:{ayah_num}"
        if key in english_lookup:
            text_en = escape_surql(english_lookup[key])
            trans_id = f"translation:{surah}_{ayah_num}_sahih"
            
            stmt_trans = f"""CREATE {trans_id} SET
    text_en = '{text_en}',
    translator = 'Sahih International',
    language = 'en';"""
            statements.append(stmt_trans)
            
            # Edge: verse -> translated_as -> translation
            stmt_edge = f"RELATE {verse_id} -> translated_as -> {trans_id};"
            statements.append(stmt_edge)
        
        statements.append("")
    
    statements.append("COMMIT TRANSACTION;")
    
    output_path = os.path.join(OUTPUT_DIR, "quran_juz30.surql")
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(statements))
    
    print(f"   → Generated: {output_path}")
    return len(arabic_data.get('data', {}).get('ayahs', []))

def transform_hadith():
    """Transform 40 Nawawi into hadith nodes."""
    print("📜 Transforming Hadith data...")
    
    with open(os.path.join(DATA_DIR, "hadith40.json"), 'r', encoding='utf-8') as f:
        hadith_data = json.load(f)
    
    statements = []
    statements.append("-- HADITH (40 Nawawi)")
    statements.append("-- Generated by transform_to_surql.py")
    statements.append("BEGIN TRANSACTION;")
    statements.append("")
    
    for h in hadith_data.get('hadiths', []):
        h_id = h.get('idInBook', h.get('id', 0))
        matn_ar = escape_surql(h.get('arabic', ''))
        
        # Handle nested english object: {narrator, text}
        english_obj = h.get('english', {})
        if isinstance(english_obj, dict):
            narrator = english_obj.get('narrator', '')
            text = english_obj.get('text', '')
            matn_en = escape_surql(f"{narrator} {text}".strip())
        else:
            matn_en = escape_surql(str(english_obj))
        
        hadith_id = f"hadith:nawawi_{h_id}"
        
        stmt = f"""CREATE {hadith_id} SET
    collection = 'Nawawi 40',
    hadith_number = {h_id},
    matn_ar = '{matn_ar}',
    mutability = 'CONSTANT';"""
        statements.append(stmt)
        
        # Create English translation if available
        if matn_en:
            trans_id = f"translation:nawawi_{h_id}_en"
            stmt_trans = f"""CREATE {trans_id} SET
    text_en = '{matn_en}',
    translator = 'Various',
    language = 'en';"""
            statements.append(stmt_trans)
            
            stmt_edge = f"RELATE {hadith_id} -> translated_as -> {trans_id};"
            statements.append(stmt_edge)
        
        statements.append("")
    
    statements.append("COMMIT TRANSACTION;")
    
    output_path = os.path.join(OUTPUT_DIR, "hadith_nawawi.surql")
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(statements))
    
    print(f"   → Generated: {output_path}")
    return len(hadith_data.get('hadiths', []))

def generate_master_ingest():
    """Combine all outputs into a single ingest script."""
    print("📜 Generating master ingest script...")
    
    files = ["quran_juz30.surql", "hadith_nawawi.surql"]
    
    with open(os.path.join(OUTPUT_DIR, "ingest.surql"), 'w', encoding='utf-8') as outfile:
        outfile.write("-- AL-MIZAN MASTER INGEST SCRIPT\n")
        outfile.write("-- Generated by transform_to_surql.py\n")
        outfile.write("-- Run with: surreal import --conn http://localhost:8000 --ns idc --db main ingest.surql\n\n")
        
        for fname in files:
            fpath = os.path.join(OUTPUT_DIR, fname)
            if os.path.exists(fpath):
                outfile.write(f"\n-- === {fname} ===\n")
                with open(fpath, 'r', encoding='utf-8') as infile:
                    outfile.write(infile.read())
                outfile.write("\n")
    
    print(f"   → Generated: {os.path.join(OUTPUT_DIR, 'ingest.surql')}")

def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    # Check for source data
    if not os.path.exists(os.path.join(DATA_DIR, "juz30_arabic.json")):
        print("❌ Source data not found. Run `python download_sources.py` first.")
        return
    
    verse_count = transform_quran()
    hadith_count = transform_hadith()
    generate_master_ingest()
    
    print(f"\n🎉 DONE!")
    print(f"   • {verse_count} verses")
    print(f"   • {hadith_count} hadiths")
    print(f"\nTo ingest into SurrealDB:")
    print(f"   surreal import --conn http://localhost:8000 --user root --pass root --ns idc --db main output/ingest.surql")

if __name__ == "__main__":
    main()
